// <auto-generated />
namespace PetAdopter_API.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changedPK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedPK));
        
        string IMigrationMetadata.Id
        {
            get { return "202201311556343_changed PK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
